# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utnuzVui0vZ346cCYlmZqWbjTVYIoXtS
"""

import pandas as pd
import numpy as np

df=pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()



df.shape

"""handelling the null """

df.isnull().sum()

"""Separation  out the columns which have more than 35% of the values missing in the dataset"""

drop_col=df.isnull().sum()[df.isnull().sum()>(35/100 * df.shape[0])]
drop_col

"""---

NOTE:There is no specific number after which you should drop the column. It's ust that we decided that on out own according to what we want.
"""

drop_col.index

df.drop(drop_col.index,axis=1,inplace=True)
df.isnull().sum()

df.groupby(['Embarked'])['Survived'].mean()

df.corr()

df[['Fare','Alone']].corr()

df['FamilySize']=df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis=1,inplace=True)
df.corr()

df.describe()

df['Embarked'].describe()

df.fillna(df.mean(),inplace=True)
df.isnull().sum()

df['Sex']=[0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

df['Embarked'].fillna('S',inplace=True)

"""If the person is alone he/she has less chance of surviving.
The reason might be the person who is
travelling wiht his family might be belonging to reich class might be prioritized over.

If the person is alone he/she has less chance of surviving.
The reason might be the person who is
travelling wiht his family might be belonging to reich class might be prioritized over.
"""

df['Alone']=[0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""**CONCLUSION**


*   Female passengers were prioritized over men.

*   People with high class or rich people survive at rate higher than others. The hierarchy might have been followed while saving the passengers.
 

*   Passengers travelling with their family have higher survival rate.
*   Passengers who boarded the ship at Cherboug, survived more in proportion than others.


*   The class and the survival rate are related.
*   List item






"""